In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"D:\tensor_titan\data\data.csv")
df.head(3)

   Unnamed: 0                                          statement   status
0           0                                         oh my gosh  Anxiety
1           1  trouble sleeping, confused mind, restless hear...  Anxiety
2           2  All wrong, back off dear, forward doubt. Stay ...  Anxiety

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53043 entries, 0 to 53042
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53043 non-null  int64
 1   statement   52681 non-null  object
 2   status      53043 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.2+ MB

In [6]:
df.isnull().sum()

Unnamed: 0      0
statement     362
status          0
dtype: int64

In [9]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [10]:
df.dropna(subset=["statement"], inplace=True)

In [11]:
df.isnull().sum()

statement    0
status       0
dtype: int64

In [12]:
df.head(3)

                                           statement   status
0                                         oh my gosh  Anxiety
1  trouble sleeping, confused mind, restless hear...  Anxiety
2  All wrong, back off dear, forward doubt. Stay ...  Anxiety